sudo: required
services:
    - docker
    
before_install:
    - docker build -t austinnchristensen/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true austinnchristensen/docker-react npm run test
